### ISSUE TITLE
Странное зацикливание при подключении

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#10]
В некоторых случаях, особенно при высокой нагрузке на сеть, появляется странный эффект, когда сервер в ответ на любой запрос отвечает одной и той же ошибкой. Скорее всего, это ошибка сервера, однако стоит убедиться в этом.

```
Версия приложения: 1.3-18
> 16 Feb 2016 5:16:04 pm
>> Проверка доступа в интернет
java.io.EOFException
at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:95)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
at pw.thedrhax.httpclient.HttpRequest.connect(HttpRequest.java:116)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:67)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:89)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.isConnected(AuthenticatorStat.java:49)
at pw.thedrhax.mosmetro.authenticator.Authenticator.connect(Authenticator.java:41)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.connect(AuthenticatorStat.java:37)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:113)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:100)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

<< Все проверки пройдены
>> Подключаюсь...
>>> Получение перенаправления на страницу авторизации
<HTML><HEAD><TITLE> Web Authentication Redirect</TITLE><META http-equiv="Cache-control" content="no-cache"><META http-equiv="Pragma" content="no-cache"><META http-equiv="Expires" content="-1"><META http-equiv="refresh" content="1; URL=http://login.wi-fi.ru/am/UI/Login?rand=ftExOq1f&org=mac&service=coa&client_mac=d0-22-be-cf-bc-64&ForceAuth=true"></HEAD></HTML>

https://login.wi-fi.ru/am/UI/Login?rand=ftExOq1f&org=mac&service=coa&client_mac=d0-22-be-cf-bc-64&ForceAuth=true
>>> Получение страницы авторизации
<html><head><meta http-equiv="Pragma" content="no-cache"><meta http-equiv="Expires" content="-1"><meta http-equiv="Cache-Control" content="no-cache,no-store,must-revalidate"><meta name="robots" content="noindex, nofollow" /><meta http-equiv="Content-Type" content="text/html;charset=utf-8"><noscript><meta http-equiv="refresh" content="1; url=http://login.wi-fi.ru/am/UI/Login?rand=ftExOq1f&org=mac&service=coa&client_mac=d0-22-be-cf-bc-64&ForceAuth=true"></noscript><title>Переадресация</title></head> 
<body><script id="redirect" type="text/javascript"> 
<!-- 
location.href="http://login.wi-fi.ru/am/UI/Login?rand=ftExOq1f&org=mac&service=coa&client_mac=d0-22-be-cf-bc-64&ForceAuth=true"; 
//--> 
</script><a href="http://login.wi-fi.ru/am/UI/Login?rand=ftExOq1f&org=mac&service=coa&client_mac=d0-22-be-cf-bc-64&ForceAuth=true">Нажмите на ссылку, если переход не произошел автоматически</a></body></html>

>>> Отправка формы авторизации
<html><head><meta http-equiv="Pragma" content="no-cache"><meta http-equiv="Expires" content="-1"><meta http-equiv="Cache-Control" content="no-cache,no-store,must-revalidate"><meta name="robots" content="noindex, nofollow" /><meta http-equiv="Content-Type" content="text/html;charset=utf-8"><noscript><meta http-equiv="refresh" content="1; url=http://login.wi-fi.ru/am/UI/Login?rand=ftExOq1f&org=mac&service=coa&client_mac=d0-22-be-cf-bc-64&ForceAuth=true"></noscript><title>Переадресация</title></head> 
<body><script id="redirect" type="text/javascript"> 
<!-- 
location.href="http://login.wi-fi.ru/am/UI/Login?rand=ftExOq1f&org=mac&service=coa&client_mac=d0-22-be-cf-bc-64&ForceAuth=true"; 
//--> 
</script><a href="http://login.wi-fi.ru/am/UI/Login?rand=ftExOq1f&org=mac&service=coa&client_mac=d0-22-be-cf-bc-64&ForceAuth=true">Нажмите на ссылку, если переход не произошел автоматически</a></body></html>

>>> Отправка второй формы авторизации
<html><head><meta http-equiv="Pragma" content="no-cache"><meta http-equiv="Expires" content="-1"><meta http-equiv="Cache-Control" content="no-cache,no-store,must-revalidate"><meta name="robots" content="noindex, nofollow" /><meta http-equiv="Content-Type" content="text/html;charset=utf-8"><noscript><meta http-equiv="refresh" content="1; url=http://login.wi-fi.ru/am/UI/Login?rand=ftExOq1f&org=mac&service=coa&client_mac=d0-22-be-cf-bc-64&ForceAuth=true"></noscript><title>Переадресация</title></head> 
<body><script id="redirect" type="text/javascript"> 
<!-- 
location.href="http://login.wi-fi.ru/am/UI/Login?rand=ftExOq1f&org=mac&service=coa&client_mac=d0-22-be-cf-bc-64&ForceAuth=true"; 
//--> 
</script><a href="http://login.wi-fi.ru/am/UI/Login?rand=ftExOq1f&org=mac&service=coa&client_mac=d0-22-be-cf-bc-64&ForceAuth=true">Нажмите на ссылку, если переход не произошел автоматически</a></body></html>

>> Проверка доступа в интернет
java.io.EOFException
at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:95)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
at pw.thedrhax.httpclient.HttpRequest.connect(HttpRequest.java:116)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:67)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:89)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.isConnected(AuthenticatorStat.java:49)
at pw.thedrhax.mosmetro.authenticator.Authenticator.connect(Authenticator.java:188)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.connect(AuthenticatorStat.java:37)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:113)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:100)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

<< Ошибка: доступ в интернет отсутствует
```

**Comment by TheDrHax** [comment]
Еще один лог с аналогичной проблемой:

```
Версия приложения: 1.3-18
> 16 февр. 2016 г. 16:39:57
>> Проверка доступа в интернет
java.io.IOException: unexpected end of stream on Connection{thedrhax.pw:80, proxy=DIRECT@ hostAddress=212.224.113.144 cipherSuite=none protocol=http/1.1} (recycle count=0)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:210)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
at pw.thedrhax.httpclient.HttpRequest.connect(HttpRequest.java:116)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:67)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:89)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.isConnected(AuthenticatorStat.java:49)
at pw.thedrhax.mosmetro.authenticator.Authenticator.connect(Authenticator.java:41)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.connect(AuthenticatorStat.java:37)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:113)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:100)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.EOFException: \n not found: size=0 content=...
at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
... 20 more

<< Все проверки пройдены
>> Подключаюсь...
>>> Получение перенаправления на страницу авторизации


https://login.wi-fi.ru/am/UI/Login?rand=Yzvq/L.d&org=mac&service=coa&client_mac=ac-22-0b-a7-d1-79&ForceAuth=true
>>> Получение страницы авторизации

Нажмите на ссылку, если переход не произошел автоматически


>>> Отправка формы авторизации

Нажмите на ссылку, если переход не произошел автоматически


>>> Отправка второй формы авторизации

Нажмите на ссылку, если переход не произошел автоматически


>> Проверка доступа в интернет
java.io.IOException: unexpected end of stream on Connection{thedrhax.pw:80, proxy=DIRECT@ hostAddress=212.224.113.144 cipherSuite=none protocol=http/1.1} (recycle count=0)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:210)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
at pw.thedrhax.httpclient.HttpRequest.connect(HttpRequest.java:116)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:67)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:89)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.isConnected(AuthenticatorStat.java:49)
at pw.thedrhax.mosmetro.authenticator.Authenticator.connect(Authenticator.java:188)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.connect(AuthenticatorStat.java:37)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:113)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:100)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.EOFException: \n not found: size=0 content=...
at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
... 20 more

<< Ошибка: доступ в интернет отсутствует

Версия приложения: 1.3-18
> 16 февр. 2016 г. 16:40:14
>> Проверка доступа в интернет
java.io.IOException: unexpected end of stream on Connection{thedrhax.pw:80, proxy=DIRECT@ hostAddress=212.224.113.144 cipherSuite=none protocol=http/1.1} (recycle count=0)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:210)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
at pw.thedrhax.httpclient.HttpRequest.connect(HttpRequest.java:116)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:67)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:89)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.isConnected(AuthenticatorStat.java:49)
at pw.thedrhax.mosmetro.authenticator.Authenticator.connect(Authenticator.java:41)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.connect(AuthenticatorStat.java:37)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:113)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:100)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.EOFException: \n not found: size=0 content=...
at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
... 20 more

<< Все проверки пройдены
>> Подключаюсь...
>>> Получение перенаправления на страницу авторизации


https://login.wi-fi.ru/am/UI/Login?rand=Yzvq/L.d&org=mac&service=coa&client_mac=ac-22-0b-a7-d1-79&ForceAuth=true
>>> Получение страницы авторизации

Нажмите на ссылку, если переход не произошел автоматически


>>> Отправка формы авторизации

Нажмите на ссылку, если переход не произошел автоматически


>>> Отправка второй формы авторизации

Нажмите на ссылку, если переход не произошел автоматически


>> Проверка доступа в интернет
java.io.IOException: unexpected end of stream on Connection{thedrhax.pw:80, proxy=DIRECT@ hostAddress=212.224.113.144 cipherSuite=none protocol=http/1.1} (recycle count=0)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:210)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
at pw.thedrhax.httpclient.HttpRequest.connect(HttpRequest.java:116)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:67)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:89)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.isConnected(AuthenticatorStat.java:49)
at pw.thedrhax.mosmetro.authenticator.Authenticator.connect(Authenticator.java:188)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.connect(AuthenticatorStat.java:37)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:113)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:100)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.EOFException: \n not found: size=0 content=...
at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
... 20 more

<< Ошибка: доступ в интернет отсутствует
```

**Comment by TheDrHax** [comment]
Сегодня поступило огромное количество сообщений об этой ошибке. Похоже, что это опять изменился алгоритм подключения.
