### ISSUE TITLE
Изменение алгоритма MosMetro v2

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#105]
Утром 18 января было замечено, что началось тестирование нового алгоритма, который определяется как MosMetroV2, но имеет другой адрес перенаправления. Всего поступило две жалобы, в то время как по поводу капчи продолжали приходить письма.

Судя по ответу сервера, теперь проверяется наличие каких-то Cookies, что не должно быть особой проблемой. Скорее всего, это получится реализовать прямо в MosMetroV2, но в крайнем случае можно создать и MosMetroV3.

```
17 янв. 2017 г. 8:20:16 AM
Определение названия сети
Поиск подходящего алгоритма для сети MosMetro_Free
Версия приложения: 1.7.2-50
Подключение к сети MosMetro_Free
Проверка доступа в интернет
<html>
<head>
  <title> Web Authentication Redirect</title>
  <meta http-equiv="Cache-control" content="no-cache">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="-1">
  <meta http-equiv="refresh" content="1; URL=http://auth.wi-fi.ru/identification?segment=metro">
</head>
<body>
</body>
</html>
http://auth.wi-fi.ru/identification?segment=metro
Версия алгоритма: 2
Получение страницы авторизации
<html>
<head>
  <meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport">
  <link rel="stylesheet" media="screen" href="/assets/auth/application-20dfe456eabaec4a528993f85133e16e68916b9695bff14949b872d845737d20.css">
</head>
<body>
  <div class="branding-header" style="z-index: 5 !important">
   <a class="header-item" href="http://login.wi-fi.ru/docs/offers/offer_auth.pdf">
    <div class="branding-header__offer">
     By pressing “Connect to the Internet” you accept the user agreement terms.
    </div></a>
   <a class="header-item" href="http://login.wi-fi.ru/vmetro/faq?lang=ru&amp;client_mac=">
    <div class="branding-header__support">
     Support
    </div></a>
   <a class="header-item" href="/warn/cookies?lang=ru">
    <div class="branding-header__lang russian">
     Русский
    </div></a>
  </div>
  <div class="auto-auth-view">
   <div class="content">
    <div class="message">
     Sorry, an error occurred
     <br>
     <br>In order to continue, enable Cookies support in current browser.
     <br>Please, try again or follow the
     <a href="/">link</a>.
    </div>
   </div>
  </div>
</body>
</html>
<html>
<head>
  <meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport">
  <link rel="stylesheet" media="screen" href="/assets/auth/application-20dfe456eabaec4a528993f85133e16e68916b9695bff14949b872d845737d20.css">
</head>
<body>
  <div class="branding-header" style="z-index: 5 !important">
   <a class="header-item" href="http://login.wi-fi.ru/docs/offers/offer_auth.pdf">
    <div class="branding-header__offer">
     By pressing “Connect to the Internet” you accept the user agreement terms.
    </div></a>
   <a class="header-item" href="http://login.wi-fi.ru/vmetro/faq?lang=ru&amp;client_mac=">
    <div class="branding-header__support">
     Support
    </div></a>
   <a class="header-item" href="/warn/cookies?lang=ru">
    <div class="branding-header__lang russian">
     Русский
    </div></a>
  </div>
  <div class="auto-auth-view">
   <div class="content">
    <div class="message">
     Sorry, an error occurred
     <br>
     <br>In order to continue, enable Cookies support in current browser.
     <br>Please, try again or follow the
     <a href="/">link</a>.
    </div>
   </div>
  </div>
</body>
</html>
Отправка формы авторизации
java.lang.Exception: Meta tag not found
at pw.thedrhax.mosmetro.httpclient.Client.parseMetaContent(Client.java:118)
at pw.thedrhax.mosmetro.authenticator.networks.MosMetro.connect(MosMetro.java:215)
at pw.thedrhax.mosmetro.authenticator.Authenticator.start(Authenticator.java:69)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:151)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:128)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)

Ошибка: сервер не ответил или вернул ошибку
17 янв. 2017 г. 8:20:16 AM
```

**Comment by TheDrHax** [comment]
Похоже, это не изменение алгоритма, а новый вид регистрации. Поймал это перенаправление на незарегистрированном устройстве. Страница предлагает зарегистрироваться с помощью номера телефона или через ГосУслуги.
