### ISSUE TITLE
Вылет при попытке открыть ссылку без установленного браузера

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#117]
Проблема, аналогичная #116. Система не может найти Activity для открытия ссылки.

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://thedrhax.pw }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1765)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1485)
	at android.app.Activity.startActivityForResult(Activity.java:3810)
	at android.app.Activity.startActivityForResult(Activity.java:3752)
	at android.app.Activity.startActivity(Activity.java:4081)
	at android.app.Activity.startActivity(Activity.java:4049)
	at android.preference.Preference.performClick(Preference.java:1001)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
	at android.widget.AdapterView.performItemClick(AdapterView.java:300)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3048)
	at android.widget.AbsListView$3.run(AbsListView.java:3837)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5261)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:734)
```

**Comment by TheDrHax** [comment]
По аналогии с той проблемой, нужно завернуть все вызовы в try-catch, однако это невозможно сделать в ссылках, которые прописаны в XML. То есть надо ещё и вынести все ссылки в код ИЛИ создать специальный Activity, который будет проверять наличие браузера.
