### ISSUE TITLE
Подключение успешно проходит, но авторизация сбрасывается

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#13]
В некоторых случаях авторизация сбрасывается через несколько секунд после успешного подключения.

Лог такого подключения:
```
Версия приложения: 1.4-20
> Feb 22, 2016 11:57:20 AM
>> Проверка доступа в интернет
java.io.EOFException
at com.android.okhttp.internal.Util.readAsciiLine(Util.java:318)
at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
at pw.thedrhax.httpclient.HttpRequest.connect(HttpRequest.java:116)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:67)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:89)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.isConnected(AuthenticatorStat.java:49)
at pw.thedrhax.mosmetro.authenticator.Authenticator.connect(Authenticator.java:98)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.connect(AuthenticatorStat.java:37)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:124)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:110)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

<< Все проверки пройдены
>> Подключаюсь...
>>> Получение начального перенаправления
<html>
<head>
  <title> Web Authentication Redirect</title>
  <meta http-equiv="Cache-control" content="no-cache">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="-1">
  <meta http-equiv="refresh" content="1; URL=http://login.wi-fi.ru/am/UI/Login?rand=W6X74uPO&amp;org=mac&amp;service=coa&amp;client_mac=b4-ef-39-45-3c-77&amp;ForceAuth=true">
</head>
<body> 
</body>
</html>
http://login.wi-fi.ru/am/UI/Login?rand=W6X74uPO&org=mac&service=coa&client_mac=b4-ef-39-45-3c-77&ForceAuth=true
>>> Получение начальной страницы
<!doctype html>
<html>
<head>
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="-1">
  <meta http-equiv="Cache-Control" content="no-cache,no-store,must-revalidate">
  <meta name="robots" content="noindex, nofollow"> 
  <meta charset="utf-8"> 
  <title></title> 
  <meta http-equiv="refresh" content="6;URL=?rand=W6X74uPO&amp;org=mac&amp;service=coa&amp;client_mac=b4-ef-39-45-3c-77&amp;ForceAuth=true&amp;adbtoken=ec60eb2fd2aa9249424d5a59a21a8e0b" id="r1"> 
  <meta name="referrer" content="always"> 
  <meta http-equiv="Pragma" content="no-cache"> 
  <meta http-equiv="Expires" content="-1"> 
  <meta http-equiv="Cache-Control" content="no-cache,no-store,must-revalidate"> 
  <meta name="robots" content="noindex, nofollow"> 
  <link rel="icon" href="/favicon.ico" type="image/x-icon"> 
</head> 
<body> 
  <form id="submit-form" method="post" action="https://login.wi-fi.ru/am/UI/Login?rand=W6X74uPO&amp;org=mac&amp;service=coa&amp;client_mac=b4-ef-39-45-3c-77&amp;ForceAuth=true"> 
   <input id="hash" type="hidden" name="IDToken1" value="ec60eb2fd2aa9249424d5a59a21a8e0b"> 
   <input type="hidden" name="csrf.sign" value="c8a1ae1a72ace20f89b691c82c3715fb0136145572ffc9bdf46d981318f05459">
   <input type="hidden" name="csrf.ts" value="1456131437711">
  </form>  
  <img src="http://ads.adfox.ru/220463/getCode?p1=buhvd&amp;p2=v&amp;pe=b&amp;pfc=bezbz&amp;pfb=dksmt&amp;pr=eslgyih" onload="load()" onerror="error()" width="1" height="1" style="visibility:hidden">   
</body>
</html>
IDToken1=ec60eb2fd2aa9249424d5a59a21a8e0b&csrf.sign=c8a1ae1a72ace20f89b691c82c3715fb0136145572ffc9bdf46d981318f05459&csrf.ts=1456131437711
>>> Получение страницы авторизации
<!doctype html>
<html class="no-js">
<head>
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="-1">
  <meta http-equiv="Cache-Control" content="no-cache,no-store,must-revalidate">
  <meta name="robots" content="noindex, nofollow"> 
  <meta charset="utf-8"> 
  <title>Авторизация Wi-Fi. Войти в Интернет</title> 
  <meta name="referrer" content="always">  
  <link rel="dns-prefetch" href="//static.wi-fi.ru"> 
  <link rel="dns-prefetch" href="//static0.wi-fi.ru"> 
  <link rel="dns-prefetch" href="//creative.wi-fi.ru">       
  <meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport"> 
  <meta content="ЗАО «МаксимаТелеком»" name="author"> 
  <link rel="icon" href="/am/favicon.ico" type="image/x-icon"> 
  <link rel="shortcut icon" href="/am/favicon.ico" type="image/x-icon"> 
</head> 
<body> 
  <ul id="header" class="nav"> 
   <li class="nav__i nav__i_agreement">
    <!-- 
          --><a href="http://login.wi-fi.ru/docs/offers/offer_auth.pdf" class="nav__link">Нажимая кнопку «Войти в Интернет», вы принимаете условия оферты</a></li> 
   <li class="nav__i">
    <!-- 
          --><a href="http://login.wi-fi.ru/vmetro/faq?lang=ru&amp;client_mac=b4-ef-39-45-3c-77" class="nav__link">Поддержка</a> </li> 
   <li class="nav__i nav__i_lang">
    <!-- 
          --><a class="nav__link" href="?rand=W6X74uPO&amp;org=mac&amp;service=coa&amp;client_mac=b4-ef-39-45-3c-77&amp;ForceAuth=true&amp;lang=en"> <span class="flag-icon flag-icon-uk"></span> English </a> </li> 
  </ul> 
  <div id="root"> 
   <div id="content">
    <!-- 
        -->
    <h1 class="welcome"> Добро пожаловать в Wi‑Fi зону Московского Метрополитена </h1> 
   </div> 
   <div id="footer"> 
    <form id="auth-form" autocomplete="off" method="post"> 
     <input id="promogoto" data-test="test" name="promogoto" type="hidden" value=""> 
     <input id="IDButton" name="IDButton" type="hidden" value="Confirm"> 
     <button id="i-btn-default" type="submit" class="btn">Войти в Интернет</button> 
     <input type="hidden" name="csrf.sign" value="adbc57799bfad9a7e48fdba5b537fff66eb582d68501889e477c1c8c765f988c">
     <input type="hidden" name="csrf.ts" value="1456131437826">
    </form> 
    <a id="join-internet" class="btn" href="#">Войти в Интернет</a> 
    <a id="premium" href="https://login.wi-fi.ru/am/UI/Login?org=mac&amp;service=seamless&amp;goto=https%3A%2F%2Fcabinet.wi-fi.ru%2Fpremium" class="btn btn_premium">Отключить авторизацию</a> 
   </div> 
  </div> 
  <div id="loader" class="l-loader">
   <div class="loader"></div>
  </div> 
  <div id="adfox-events"></div>     
</body>
</html>
promogoto=&IDButton=Confirm&csrf.sign=adbc57799bfad9a7e48fdba5b537fff66eb582d68501889e477c1c8c765f988c&csrf.ts=1456131437826
>>> Отправка формы авторизации
<html>
<head></head>
<body>
  You are being 
  <a href="https://login.wi-fi.ru/am/UI/Login?org=mac&amp;service=seamless&amp;goto=http%3A%2F%2Fwi-fi.ru%2F">redirected</a>. 
</body>
</html>
>> Проверка доступа в интернет
<< Соединение успешно установлено :3
< Feb 22, 2016 11:57:21 AM
```

**Comment by TheDrHax** [comment]
Похоже, что это неисправность самой сети.
