### ISSUE TITLE
Капча на МЦК вызывает ошибку

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#131]
Судя по сообщениям, на МЦК начали менять алгоритм. Парсер из MosMetroV2 перестал распознавать капчу, поэтому он доходит до проверки соединения, где ожидается JSON ответ от сервера.

```
5 мар. 2017 г. 7:35:39
Определение провайдера…
Версия приложения: 1.7.4-55
Название алгоритма: MosMetroV2
Проверка доступа в интернет
<!doctype html>
<html>
 <head> 
  <meta charset="utf-8"> 
  <title>wi-fi</title> 
  <meta http-equiv="refresh" content="0;https://auth.wi-fi.ru?segment=mcc"> 
 </head> 
 <body>  
 </body>
</html>
https://auth.wi-fi.ru?segment=mcc
Получение перенаправления
<html>
 <head>
  <meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport">
  <link rel="stylesheet" media="screen" href="/assets/auth/application-20dfe456eabaec4a528993f85133e16e68916b9695bff14949b872d845737d20.css">
 </head>
 <body>
  <img class="data_pixels" src="http://ads.adfox.ru/220463/getDefaultImage?p1=buxxf&amp;amp;p2=v" alt="Getdefaultimage?p1=buxxf&amp;amp;p2=v">
  <img class="data_pixels" src="http://ads.adfox.ru/220463/getCode?p1=buhvd&amp;amp;p2=v&amp;amp;pe=b&amp;amp;pfc=bezbz&amp;amp;pfb=dksmt&amp;amp;pr=eslgyih" alt="Getcode?p1=buhvd&amp;amp;p2=v&amp;amp;pe=b&amp;amp;pfc=bezbz&amp;amp;pfb=dksmt&amp;amp;pr=eslgyih">
  <img class="data_pixels" src="http://top-fwz1.mail.ru/counter?id=701848;js=na" alt="Counter?id=701848;js=na">
  <img class="data_pixels" src="http://banners.adfox.ru/transparent.gif" alt="Transparent">
  <div class="no-js-view">
   <div class="error-view" style="display: block;">
    <h1 class="message">In order to continue, enable JavaScript execution in current browser</h1>
   </div>
  </div>
 </body>
</html>
Получение страницы авторизации
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html class="no-js">
 <head>
  <meta charset="utf-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta content="no-cache,no-store,must-revalidate" http-equiv="Cache-Control">
  <meta content="no-cache" http-equiv="Pragma">
  <meta content="-1" http-equiv="Expires">
  <meta content="noindex, nofollow" name="robots">
  <meta content="always" name="referrer">
  <meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport">
  <link href="/favicon.ico" rel="icon" type="image/x-icon">
  <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon">
  <title>Wi-Fi Authorization</title>
  <meta content="JSC “MaximaTelecom”" name="author">
  <meta name="csrf-param" content="authenticity_token"> 
  <meta name="csrf-token" content="ECTO7q4sjCp1YAsc2U3L5y11i7eYqNummaM0yRr2Fe8CAwl4IxacUfJpAneuIyWx2c4THnrjCtkhYtschCctBQ==">
 </head>
 <body>
  <div id="app"></div>
 </body>
</html>
Отправка формы авторизации
<html>
 <head>
  <meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport">
  <link rel="stylesheet" media="screen" href="/assets/auth/application-20dfe456eabaec4a528993f85133e16e68916b9695bff14949b872d845737d20.css">
 </head>
 <body>
  <div class="branding-header" style="z-index: 5 !important">
   <a class="header-item" href="http://login.wi-fi.ru/docs/offers/offer_auth.pdf">
    <div class="branding-header__offer">
     By pressing “Connect” you accept the user agreement terms.
    </div></a>
   <a class="header-item" href="http://login.wi-fi.ru/vmetro/faq?lang=ru">
    <div class="branding-header__support">
     Support
    </div></a>
   <a class="header-item" href="/auto_auth?lang=ru&amp;segment=metro">
    <div class="branding-header__lang russian">
     Русский
    </div></a>
  </div>
  <div class="auto-auth-view">
   <div class="content">
    <div class="message">
     Уважаемый пользователь.
     <br>Возможно, на Вашем устройстве установлено программное обеспечение, производящее автоматическую авторизацию, что противоречит «Условиям пользования Услугами». Для доступа к сети Интернет Вам необходимо удалить данную программу или внести корректировки в настройки браузера. Для автоматического подключения и доступа к сети Интернет без просмотра рекламы Вы можете подключить Услугу&nbsp;
     <a href="https://pay.wi-fi.ru">«Как&nbsp;дома»</a>. Если данное сообщение Вы получили по ошибке, то введите код с картинки ниже.
    </div>
   </div>
   <form class="captcha__container" action="/auto_auth?segment=metro" accept-charset="UTF-8" method="post">
    <input name="utf8" type="hidden" value="✓">
    <input type="hidden" name="authenticity_token" value="/laAhDxnJoq2Y3CGL7uwd8Mk4L5IGCnHKw3gEUsKgF3scUcSsV028TFqee1Y1V4hN594F6pT+LiTzA/E1du4tw==">
    <img class="captcha__image" alt="Captcha" src="/rucaptcha/">
    <div class="captcha__controls">
     <input class="captcha__input form-control" placeholder="Введите текст с картинки" name="_rucaptcha" type="text" autocorrect="off" autocapitalize="off" pattern="[0-9a-z]*" maxlength="4" autocomplete="off">
     <input type="submit" name="commit" value="OK" class="captcha__submit" data-disable-with="OK">
    </div>
   </form>
  </div>
 </body>
</html>
Проверка доступа в интернет
Unexpected character (<) at position 0.
	at org.json.simple.parser.Yylex.yylex(Yylex.java:610)
	at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:118)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
	at pw.thedrhax.mosmetro.authenticator.providers.MosMetroV2$10.run(MosMetroV2.java:354)
	at pw.thedrhax.mosmetro.authenticator.Provider.start(Provider.java:230)
	at pw.thedrhax.mosmetro.services.ConnectionService.connect(ConnectionService.java:228)
	at pw.thedrhax.mosmetro.services.ConnectionService.main(ConnectionService.java:334)
	at pw.thedrhax.mosmetro.services.ConnectionService.onHandleIntent(ConnectionService.java:290)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by TheDrHax** [comment]
Не подтвердилось. Выждем ещё недельку, но релиз задерживать не буду.

**Comment by TheDrHax** [comment]
Дамп собрал. Посмотрим, что они поменяли.

**Comment by TheDrHax** [comment]
Исправление 	d82aa1d позволило избавиться от этой ошибки, однако его нужно доработать, прежде чем выпускать в основную ветку. [Аналог goto](https://github.com/TheDrHax/mosmetro-android/commit/d82aa1da6d691a1ac93211116fa3b529d150bf7a#diff-f53b4865da06cd3b164697d991b11871R165) вносит частицу непредсказуемости.
