### ISSUE TITLE
Капча не загружается

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#139]
```
[+1020] Ошибка: не удалось загрузить изображение
[+0001] java.lang.Exception: Empty response: 200
	at pw.thedrhax.mosmetro.httpclient.clients.OkHttp.getInputStream(OkHttp.java:232)
	at pw.thedrhax.mosmetro.httpclient.Client$3.body(Client.java:126)
	at pw.thedrhax.mosmetro.httpclient.Client$3.body(Client.java:123)
	at pw.thedrhax.mosmetro.httpclient.Client$RetryOnException.run(Client.java:89)
	at pw.thedrhax.mosmetro.httpclient.Client.getInputStream(Client.java:128)
	at pw.thedrhax.mosmetro.activities.CaptchaDialog$2$1.doInBackground(CaptchaDialog.java:76)
	at pw.thedrhax.mosmetro.activities.CaptchaDialog$2$1.doInBackground(CaptchaDialog.java:71)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

![image](https://cloud.githubusercontent.com/assets/6968908/25034945/05429440-20f3-11e7-8732-c1a1c489fa32.png)

**Comment by TheDrHax** [comment]
В b7c8b02bb06632b9dc919a3ea7786c40fd95d2eb был исправлен вывод кода ошибки. Это должно предоставить больше информации по поводу проблемы.
