### ISSUE TITLE
Возможно, алгоритм снова обновляется

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#15]
Получил такой лог:

```
Версия приложения: 1.4-20
> 24 Фев 2016 г. 21:00:44
>> Проверка доступа в интернет
java.io.EOFException
at com.android.okhttp.internal.Util.readAsciiLine(Util.java:318)
at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:147)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:795)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
at pw.thedrhax.httpclient.HttpRequest.connect(HttpRequest.java:116)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:67)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:89)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.isConnected(AuthenticatorStat.java:49)
at pw.thedrhax.mosmetro.authenticator.Authenticator.connect(Authenticator.java:98)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.connect(AuthenticatorStat.java:37)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:124)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:110)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

<< Все проверки пройдены
>> Подключаюсь...
>>> Получение начального перенаправления
<html>
<head>
  <title> Web Authentication Redirect</title>
  <meta http-equiv="Cache-control" content="no-cache">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="-1">
  <meta http-equiv="refresh" content="1; URL=http://authrad.vmet.ro/?switch_url=http://1.1.1.1/login.html&amp;ap_mac=c4:14:3c:7a:70:40&amp;client_mac=48:5a:3f:51:ff:66&amp;wlan=MosMetro_Free&amp;redirect=vmet.ro/">
</head>
<body> 
</body>
</html>
http://authrad.vmet.ro/?switch_url=http://1.1.1.1/login.html&ap_mac=c4:14:3c:7a:70:40&client_mac=48:5a:3f:51:ff:66&wlan=MosMetro_Free&redirect=vmet.ro/
>>> Получение начальной страницы
java.net.ConnectException: failed to connect to authrad.vmet.ro/10.1.1.5 (port 80) after 2000ms: isConnected failed: ECONNREFUSED (Connection refused)
at libcore.io.IoBridge.isConnected(IoBridge.java:223)
at libcore.io.IoBridge.connectErrno(IoBridge.java:161)
at libcore.io.IoBridge.connect(IoBridge.java:112)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
at java.net.Socket.connect(Socket.java:833)
at com.android.okhttp.internal.Platform.connectSocket(Platform.java:152)
at com.android.okhttp.Connection.connect(Connection.java:949)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:405)
at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:343)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:289)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
at pw.thedrhax.httpclient.HttpRequest.connect(HttpRequest.java:116)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:67)
at pw.thedrhax.httpclient.HttpClient.navigate(HttpClient.java:89)
at pw.thedrhax.mosmetro.authenticator.Authenticator.getPageContent(Authenticator.java:51)
at pw.thedrhax.mosmetro.authenticator.Authenticator.connect(Authenticator.java:141)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.connect(AuthenticatorStat.java:37)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:124)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:110)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: libcore.io.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
at libcore.io.IoBridge.isConnected(IoBridge.java:208)
... 27 more

<<< Ошибка: начальная страница не получена
```

Authrad.vmet.ro — это что-то новое. Раньше такого не видел.

**Comment by TheDrHax** [comment]
Поступило 3 сообщения о такой ошибке:

```
>>> Получение начального перенаправления
<html>
<head>
  <title> Web Authentication Redirect</title>
  <meta http-equiv="Cache-control" content="no-cache">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="-1">
  <meta http-equiv="refresh" content="1; URL=http://login.wi-fi.ru/am/UI/Login?rand=1HjCREkZ&amp;org=mac&amp;service=coa&amp;client_mac=00-03-aa-d9-7e-cb&amp;ForceAuth=true">
</head>
<body> 
</body>
</html>
http://login.wi-fi.ru/am/UI/Login?rand=1HjCREkZ&org=mac&service=coa&client_mac=00-03-aa-d9-7e-cb&ForceAuth=true
>>> Получение начальной страницы
<!doctype html>
<html class="no-js">
<head>
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="-1">
  <meta http-equiv="Cache-Control" content="no-cache,no-store,must-revalidate">
  <meta name="robots" content="noindex, nofollow"> 
  <meta charset="utf-8"> 
  <title>Авторизация Wi-Fi. Войти в Интернет</title> 
  <meta name="referrer" content="always">  
  <link rel="dns-prefetch" href="//static.wi-fi.ru"> 
  <link rel="dns-prefetch" href="//static0.wi-fi.ru"> 
  <link rel="dns-prefetch" href="//creative.wi-fi.ru">       
  <meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport"> 
  <meta content="ЗАО «МаксимаТелеком»" name="author"> 
  <link rel="icon" href="/am/favicon.ico" type="image/x-icon"> 
  <link rel="shortcut icon" href="/am/favicon.ico" type="image/x-icon"> 
</head> 
<body> 
  <ul id="header" class="nav"> 
   <li class="nav__i nav__i_agreement">
    <!-- 
          --><a href="http://login.wi-fi.ru/docs/offers/offer_auth.pdf" class="nav__link">Нажимая кнопку «Войти в Интернет», вы принимаете условия оферты</a></li> 
   <li class="nav__i">
    <!-- 
          --><a href="http://login.wi-fi.ru/vmetro/faq?lang=ru&amp;client_mac=00-03-aa-d9-7e-cb" class="nav__link">Поддержка</a> </li> 
   <li class="nav__i nav__i_lang">
    <!-- 
          --><a class="nav__link" href="?rand=1HjCREkZ&amp;org=mac&amp;service=coa&amp;client_mac=00-03-aa-d9-7e-cb&amp;ForceAuth=true&amp;lang=en"> <span class="flag-icon flag-icon-uk"></span> English </a> </li> 
  </ul> 
  <div id="root"> 
   <div id="content">
    <!-- 
        -->
    <h1 class="welcome"> Добро пожаловать в Wi‑Fi зону Московского Метрополитена </h1> 
   </div> 
   <div id="footer"> 
    <form id="auth-form" autocomplete="off" method="post"> 
     <input id="promogoto" data-test="test" name="promogoto" type="hidden" value=""> 
     <input id="IDButton" name="IDButton" type="hidden" value="Confirm"> 
     <button id="i-btn-default" type="submit" class="btn">Войти в Интернет</button> 
     <input type="hidden" name="csrf.sign" value="b843ff5dc2f1f3cb50b1b867a9e78ca8e71c259a953dfa4d2c3e508bf3be3b3c">
     <input type="hidden" name="csrf.ts" value="1456769420144">
    </form> 
    <a id="join-internet" class="btn" href="#">Войти в Интернет</a> 
    <a id="premium" href="https://login.wi-fi.ru/am/UI/Login?org=mac&amp;service=seamless&amp;goto=https%3A%2F%2Fcabinet.wi-fi.ru%2Fpremium" class="btn btn_premium">Отключить авторизацию</a> 
   </div> 
  </div> 
  <div id="loader" class="l-loader">
   <div class="loader"></div>
  </div> 
  <div id="adfox-events"></div>     
</body>
</html>
promogoto=&IDButton=Confirm&csrf.sign=b843ff5dc2f1f3cb50b1b867a9e78ca8e71c259a953dfa4d2c3e508bf3be3b3c&csrf.ts=1456769420144
>>> Получение страницы авторизации
<html>
<head></head>
<body>
  You are being 
  <a href="https://login.wi-fi.ru/am/UI/Login?org=mac&amp;service=seamless&amp;goto=http%3A%2F%2Fwi-fi.ru%2F">redirected</a>. 
</body>
</html>
<<< Ошибка: форма авторизации не найдена
```
Похоже, алгоритм опять обновляется местами.

**Comment by TheDrHax** [comment]
Сообщение от одного из пользователей: подключение при этой ошибке проходит.
Значит просто исчез один из этапов авторизации, что будет довольно легко починить.
