### ISSUE TITLE
Возможно, готовится изменение алгоритма

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#28]
Снова поступило сообщение об ошибке, в котором фигурирует адрес authrad.vmet.ro. Сам я с таким не сталкивался, но такая проблема упоминалась в #15.
```
>>> Получение начального перенаправления
<html>
<head>
  <title> Web Authentication Redirect</title>
  <meta http-equiv="Cache-control" content="no-cache">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="-1">
  <meta http-equiv="refresh" content="1; URL=http://authrad.vmet.ro/?switch_url=http://1.1.1.1/login.html&amp;ap_mac=5c:a4:8a:93:e8:b0&amp;client_mac=00:0a:f5:89:e2:58&amp;wlan=MosMetro_Free&amp;redirect=vmet.ro/">
</head>
<body> 
</body>
</html>
http://authrad.vmet.ro/?switch_url=http://1.1.1.1/login.html&ap_mac=5c:a4:8a:93:e8:b0&client_mac=00:0a:f5:89:e2:58&wlan=MosMetro_Free&redirect=vmet.ro/
>>> Получение страницы авторизации
java.net.ConnectException: Failed to connect to authrad.vmet.ro/10.1.1.5:80
at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:142)
at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
at okhttp3.RealCall.getResponse(RealCall.java:240)
at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
at okhttp3.RealCall.execute(RealCall.java:57)
at pw.thedrhax.mosmetro.authenticator.Authenticator.getPageContent(Authenticator.java:116)
at pw.thedrhax.mosmetro.authenticator.Authenticator.connect(Authenticator.java:205)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.connect(AuthenticatorStat.java:34)
at pw.thedrhax.mosmetro.services.ConnectionService.connect(ConnectionService.java:199)
at pw.thedrhax.mosmetro.services.ConnectionService.onHandleIntent(ConnectionService.java:229)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.os.HandlerThread.run(HandlerThread.java:61)

<<< Ошибка: страница авторизации не получена
```

**Comment by TheDrHax** [comment]
Ручное подключение тоже не работает при такой ошибке, поэтому исправить не получится.
