### ISSUE TITLE
Проблемы с Mi Phone

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#29]
От нескольких пользователей поступило сообщение о неработающем подключении. Проблемы объединяются подписью "Отправлено с Mi Phone" и отсутствием переносов строк в логе.

Вот участок лога (переносы строк добавлены):
```
> 17 марта 2016 г. 16:53:58
>> Ожидание получения IP адреса...
<< IP адрес получен в течение 0 секунд
Версия приложения: 1.5-28
>> Проверка доступа в интернет
<< Ошибка: Сеть недоступна или не отвечает 
```

Пока что информации недостаточно для того, чтобы точно определить причину этой ошибки. Известно только то, что подключение через браузер при этом работает.

Нужно добавить проверку подключения в отладочный лог, чтобы узнать об этой проблеме больше.

**Comment by TheDrHax** [comment]
Вот сборка, которая включает предыдущий коммит: [experimental-v28-b41](https://local.thedrhax.pw/jenkins/job/MosMetro-Android/branch/experimental/41/artifact/bin/MosMetro-experimental-v28-b41-signed.apk).

Если у вас возникает та же проблема, установите эту сборку и отправьте отчет, когда проблема снова проявится.

**Comment by TheDrHax** [comment]
С помощью последней сборки удалось получить более подробные сведения о проблеме:
```
> 18 марта 2016 г. 17:15:11
>> Ожидание получения IP адреса...
<< IP адрес получен в течение 0 секунд
Версия приложения: experimental-28
>> Проверка доступа в интернет
java.net.UnknownHostException: Unable to resolve host "vmet.ro": No address associated with hostname
at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
at java.net.InetAddress.getAllByName(InetAddress.java:214)
at okhttp3.Dns$1.lookup(Dns.java:39)
at okhttp3.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:173)
at okhttp3.internal.http.RouteSelector.nextProxy(RouteSelector.java:139)
at okhttp3.internal.http.RouteSelector.next(RouteSelector.java:81)
at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97) 
at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
at okhttp3.RealCall.getResponse(RealCall.java:240)
at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
at okhttp3.RealCall.execute(RealCall.java:57)
at pw.thedrhax.mosmetro.authenticator.Authenticator.getPageContent(Authenticator.java:110)
at pw.thedrhax.mosmetro.authenticator.Authenticator.isConnected(Authenticator.java:63)
at pw.thedrhax.mosmetro.authenticator.Authenticator.connect(Authenticator.java:148)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.connect(AuthenticatorStat.java:34)
at pw.thedrhax.mosmetro.services.ConnectionService.connect(ConnectionService.java:199)
at pw.thedrhax.mosmetro.services.ConnectionService.onHandleIntent(ConnectionService.java:229)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: libcore.io.GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)
at libcore.io.Posix.getaddrinfo(Native Method)
at libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:61)
at java.net.InetAddress.lookupHostByName(InetAddress.java:405)
... 25 more
<< Ошибка: Сеть недоступна или не отвечает
```

**Comment by TheDrHax** [comment]
Теперь эта проблема должна исправиться, если хотя-бы один раз запустить ручное подключение при наличии доступа в интернет. Нужно что-то придумать, чтобы ручное подключение не нужно было запускать, но это уже после получения сигнала о решенной проблеме.

**Comment by TheDrHax** [comment]
Использование BetterDNS не помогло. Приложение не получило перенаправление от сервера, но подключения, на самом деле, не произошло. **(не подтверждено)**

```
> 21 марта 2016 г. 10:10:33
Версия приложения: experimental-28
>> Проверка доступа в интернет java.lang.Exception: Перенаправление не найдено
at pw.thedrhax.mosmetro.authenticator.Authenticator.parseMetaRedirect(Authenticator.java:92)
at pw.thedrhax.mosmetro.authenticator.Authenticator.isConnected(Authenticator.java:71)
at pw.thedrhax.mosmetro.authenticator.Authenticator.connect(Authenticator.java:148)
at pw.thedrhax.mosmetro.authenticator.AuthenticatorStat.connect(AuthenticatorStat.java:38)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:118) at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:98) at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
<< Уже подключено
< 21 марта 2016 г. 10:10:34 
```

**Comment by TheDrHax** [comment]
Похоже, что проблема была не в приложении, а разрешениях, выданных системой. Остается только протестировать основную версию, чтобы убедиться в этом.

**Comment by TheDrHax** [comment]
Решение добавлено в [wiki](https://github.com/TheDrHax/mosmetro-android/wiki#%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BD%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D0%BD%D0%B0-%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%B0%D1%85-%D0%BF%D0%BE%D0%B4-%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC-miui-%D0%A7%D1%82%D0%BE-%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C).
