### ISSUE TITLE
Проблема с блокировщиками рекламы

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#40]
Стало известно, что некоторые блокировщики рекламы (например AdGuard) блокируют некоторые проверки в приложении. Это приводит к тому, что приложение всегда думает, что "Сеть недоступна или не отвечает". Дело в том, что в списках блокировки присутствуют сайты example.com и vmet.ro, которые используются приложением. При внесении этих адресов в исключения, проблема пропадает. Думаю, достаточно будет не использовать эти сайты в алгоритме.

Пример лога с такой проблемой:
```
>> Проверка доступа в интернет
java.lang.Exception: Empty response
at pw.thedrhax.mosmetro.httpclient.clients.OkHttp.parseDocument(OkHttp.java:97)
at pw.thedrhax.mosmetro.httpclient.clients.OkHttp.get(OkHttp.java:66)
at pw.thedrhax.mosmetro.authenticator.networks.MosMetro.isConnected(MosMetro.java:130)
at pw.thedrhax.mosmetro.authenticator.networks.MosMetro.connect(MosMetro.java:33)
at pw.thedrhax.mosmetro.authenticator.Authenticator.start(Authenticator.java:86)
at pw.thedrhax.mosmetro.services.ConnectionService.connect(ConnectionService.java:193)
at pw.thedrhax.mosmetro.services.ConnectionService.onHandleIntent(ConnectionService.java:232)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)

<< Ошибка: Сеть недоступна или не отвечает
```

**Comment by TheDrHax** [comment]
Единственное упоминание адреса http://example.com было убрано в коммите 4ac89a61ed1ea2f68c6561f9dfff07ee0112b09e. Осталось переписать проверку интернета в классе MosMetro.

**Comment by TheDrHax** [comment]
Проверил, AdGuard больше не мешает работе приложения.
