### ISSUE TITLE
Поддержка сети MosGorTrans_Free

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#62]
Сеть MosGorTrans_Free, используемая в наземном транспорте Москвы, обслуживается двумя провайдерами: NetByNet (в транспорте) и Enforta (на остановках).

Вся разработка производится в ветке mosgortrans, которая в одностороннем порядке периодически синхронизируется с веткой master.

План действий:
- [x] Различие сетей на программном уровне: в методе MosGorTrans.isConnected()
  - NetByNet: начальная страница содержит "mosgortrans.netbynet.ru" + простое перенаправление
  - Enforta: начальная страница содержит "enforta.ru" + meta-перенаправление
- [ ] Реализовать поддержку сетей
  - [x] Поддержка NetByNet
  - [ ] Поддержка Enforta
- [x] Привести класс MosGorTrans в порядок и проверить его на стабильность (переписан с нуля)
- [x] Включить поддержку MosGorTrans_Free в ветку master
## NetByNet
- [x] Добыть дамп подключения
- [x] Реализовать алгоритм: метод MosGorTrans.connect_netbynet()
- [x] Протестировать алгоритм в наземном транспорте
- [x] Добавить поддержку сети в основную ветку
## Enforta
- [x] Добыть дамп подключения
- [ ] Реализовать алгоритм: метод MosGorTrans.connect_enforta()
  - [x] Реализовать генерацию пары логин-пароль для Enforta
    - [x] Вытащить данные для генерации с enforta.ru/login
      - Логин: "username\.value = \"(.*?)\";"
      - Выражение для пароля: "username\.value = \"(.*?)\";"
    - [x] Расчитать MD5 хэш из выражения для пароля: Использована библиотека Mozilla Rhino и [скрипт](http://hs.enforta.ru/js/devices/routeros-md5.js) с сайта Enforta. Значение MD5, полученное из стандартной библиотеки, не сходится с тем, что получается из JavaScript.
    - [x] Подставить полученные данные в форму авторизации
  - [ ] Легкие HTTP-клиенты, типа OkHttp или JSoup, несовместимы с Enforta
    - [x] OkHttp: Ошибка `java.io.IOException: unexpected end of stream on okhttp3.Address@19866665`. Решается добавлением заголовка "Connection: close", приводя к поведению, аналогичному Jsoup.
    - [x] Jsoup: Поведение отличается от браузера. При сравнении дампов оказывается, что в месте ошибки (см. [лог](https://github.com/TheDrHax/mosmetro-android/issues/62#issuecomment-248354778)) происходит отправка лишнего запроса, который никак нельзя заблокировать.
      - [x] [Собрать дамп для примера](https://github.com/TheDrHax/mosmetro-android/issues/62#issuecomment-248669143)
    - [x] Apache HttpComponents (deprecated on API > 23)
    - [x] HttpURLConnection ([http-request](http://kevinsawicki.github.io/http-request/)) — аналогично Jsoup
    - [ ] ...
- [ ] Протестировать алгоритм на остановках
- [ ] Добавить поддержку сети в основную ветку

**Comment by TheDrHax** [comment]
* [x] Реализовать генерацию пары логин-пароль для Enforta
    * [x] Вытащить данные для генерации с enforta.ru/login
        * Логин: "username\\.value = \"(.*?)\";"
        * Выражение для пароля: "username\\.value = \"(.*?)\";"
    * [x] Расчитать MD5 хэш из выражения для пароля: Использована библиотека Mozilla Rhino и [скрипт](http://hs.enforta.ru/js/devices/routeros-md5.js) с сайта Enforta. Значение MD5, полученное из стандартной библиотеки, не сходится с тем, что получается из JavaScript.
    * [x] Подставить полученные данные в форму авторизации

**Comment by TheDrHax** [comment]
* [ ] Легкие HTTP-клиенты, типа OkHttp или JSoup, несовместимы с Enforta
    * [x] OkHttp: Ошибка ```java.io.IOException: unexpected end of stream on okhttp3.Address@19866665```. Решается добавлением заголовка "Connection: close", приводя к поведению, аналогичному JSoup.
    * [x] JSoup: Поведение отличается от браузера. При сравнении дампов оказывается, что в месте ошибки (в логе ниже) происходит отправка лишнего запроса, который никак нельзя заблокировать.
        * [ ] Собрать дамп для примера
    * [ ] Apache HttpComponents — ?

```
14 сент. 2016 г. 13:50:06
Поиск подходящего алгоритма для сети MosGorTrans_Free
Версия приложения: 1.6.2-37
Подключение к сети MosGorTrans_Free
Проверка доступа в интернет
<html>
 <!--
<?xml version="1.0" encoding="UTF-8"?>
  <WISPAccessGatewayParam
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://enforta.ru/xml/WISPAccessGatewayParam.xsd">
    <Redirect>
	<AccessProcedure>1.0</AccessProcedure>
	<AccessLocation></AccessLocation>
	<LocationName></LocationName>
	<LoginURL>http://enforta.ru/login?target=xml</LoginURL>
	<MessageType>100</MessageType>
	<ResponseCode>0</ResponseCode>
    </Redirect>
  </WISPAccessGatewayParam>
-->
 <head> 
  <title></title> 
  <meta http-equiv="refresh" content="0; url=http://enforta.ru/login?dst=http%3A%2F%2Fmosgortrans.ru%2F"> 
  <meta http-equiv="pragma" content="no-cache"> 
  <meta http-equiv="expires" content="-1"> 
 </head> 
 <body>   
 </body>
</html>
Подключение к провайдеру Enforta
Получение перенаправления
<html>
 <!--
<?xml version="1.0" encoding="UTF-8"?>
  <WISPAccessGatewayParam
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://enforta.ru/xml/WISPAccessGatewayParam.xsd">
    <Redirect>
	<AccessProcedure>1.0</AccessProcedure>
	<AccessLocation></AccessLocation>
	<LocationName></LocationName>
	<LoginURL>http://enforta.ru/login?target=xml</LoginURL>
	<MessageType>100</MessageType>
	<ResponseCode>0</ResponseCode>
    </Redirect>
  </WISPAccessGatewayParam>
-->
 <head> 
  <title></title> 
  <meta http-equiv="refresh" content="0; url=http://enforta.ru/login?dst=http%3A%2F%2Fmosgortrans.ru%2F"> 
  <meta http-equiv="pragma" content="no-cache"> 
  <meta http-equiv="expires" content="-1"> 
 </head> 
 <body>   
 </body>
</html>
http://enforta.ru/login?dst=http%3A%2F%2Fmosgortrans.ru%2F
Получение начальной страницы
<html>
 <head>
  <title></title>
 </head> 
 <body> 
  <noscript> 
   <center>
    <b>JavaScript required. Enable JavaScript to continue.</b>
   </center> 
  </noscript> 
  <form name="redirect" action="http://hs.enforta.ru/" method="get"> 
   <input type="hidden" name="mac" value="DELETED"> 
   <input type="hidden" name="mac_client" value="DELETED"> 
   <input type="hidden" name="device" value="routerOS"> 
   <input type="hidden" name="ip" value="DELETED"> 
   <input type="hidden" name="username" value=""> 
   <input type="hidden" name="link-login" value="http://enforta.ru/login?dst=http%3A%2F%2Fmosgortrans.ru%2F"> 
   <input type="hidden" name="link-orig" value="http://mosgortrans.ru/"> 
   <input type="hidden" name="error" value=""> 
   <input type="hidden" name="chap-id" value="DELETED"> 
   <input type="hidden" name="chap-challenge" value="DELETED"> 
   <input type="hidden" name="link-login-only" value="http://enforta.ru/login"> 
   <input type="hidden" name="link-orig-esc" value="http%3A%2F%2Fmosgortrans.ru%2F"> 
   <input type="hidden" name="mac-esc" value="DELETED"> 
  </form>    
 </body>
</html>
Получение перенаправления
java.io.IOException: unexpected end of stream on okhttp3.Address@19866665
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:199)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:723)
	at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:81)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
	at pw.thedrhax.mosmetro.httpclient.clients.OkHttp$100000002.intercept(OkHttp.java:52)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:681)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
	at okhttp3.RealCall.getResponse(RealCall.java:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at pw.thedrhax.mosmetro.httpclient.clients.OkHttp.get(OkHttp.java:77)
	at pw.thedrhax.mosmetro.authenticator.networks.MosGorTrans.connect_enforta(MosGorTrans.java:218)
	at pw.thedrhax.mosmetro.authenticator.networks.MosGorTrans.connect(MosGorTrans.java:386)
	at pw.thedrhax.mosmetro.authenticator.Authenticator.start(Authenticator.java:63)
	at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:152)
	at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.EOFException: \n not found: size=0 content=...
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:201)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	... 23 more

Ошибка: перенаправление не получено
14 сент. 2016 г. 13:50:06
```

**Comment by TheDrHax** [comment]
Дамп подключения с использованием JSoup

```
GET /users/hotspotConnection?link-login-only=http://enforta.ru/login&device=routerOS&link-login=http://enforta.ru/login?dst=http%3A%2F%2Fmosgortrans.ru%2F&mac=DELETED&mac-esc=DELETED&link-orig=http://mosgortrans.ru/&ip=DELETED&chap-id=DELETED&link-orig-esc=http%3A%2F%2Fmosgortrans.ru%2F&chap-challenge=DELETED&mac_client=DELETED HTTP/1.1
Cookie: Cloud4wi=DELETED
Accept-Encoding: gzip
User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0.1; A0001 Build/MHC19Q)
Host: hs.enforta.ru
Connection: Keep-Alive

HTTP/1.1 200 OK
Date: Wed, 21 Sep 2016 08:25:31 GMT
Server: ATS/4.2.3
X-Powered-By: PHP/5.3.3
Set-Cookie: Wrop[SPWropWifiCloud][token]=DELETED; expires=Wed, 21-Sep-2016 09:25:31 GMT; path=/
Set-Cookie: Wrop[SPWropWifiCloud][isLogged]=deleted; expires=Tue, 22-Sep-2015 08:25:30 GMT; path=/
Set-Cookie: Wrop[SPWropWifiCloud][firstTimeLoad]=1; expires=Wed, 21-Sep-2016 09:25:31 GMT; path=/
Set-Cookie: Wrop[SPWropWifiCloud][device]=DELETED; expires=Wed, 21-Sep-2016 09:25:31 GMT; path=/
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
Content-Length: 175
Age: 307


						<html>
						</body>
						<script language="javascript" type="text/javascript">
							window.location="/";
		 				</script>
						</body>
						</html>


GET / HTTP/1.1 << Тот самый лишний запрос
Cookie: Wrop[SPWropWifiCloud][device]=DELETED; Wrop[SPWropWifiCloud][isLogged]=deleted; Cloud4wi=DELETED; Wrop[SPWropWifiCloud][firstTimeLoad]=1; Wrop[SPWropWifiCloud][token]=DELETED
Accept-Encoding: gzip
User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0.1; A0001 Build/MHC19Q)
Host: hs.enforta.ru
Connection: Keep-Alive
```

**Comment by TheDrHax** [comment]
Этот тикет сильно устарел: Netbynet теперь использует алгоритм MosMetroV2, а насчёт Enforta очень мало дельной информации. Я открою новый тикет по поводу Enforta, когда продолжу работу над этим провайдером.
