### ISSUE TITLE
Изменение алгоритма MosMetro v2 (18.11.16, вечер)

### ISSUE THREAD

**Issue by TheDrHax** [TheDrHax/mosmetro-android#68]
Похоже, опять что-то поменяли во втором алгоритме. Примерно это же происходило и с первым алгоритмом, когда его только включили. Лог не даёт полезной информации, а только показывает последствия какой-то ошибки.

План действий:
* [x] Собрать лог подключения
* [x] Собрать дамп подключения
* [x] Исправить алгоритм
* [x] Протестировать приложение

**Comment by TheDrHax** [comment]
## Лог подключения (v1.6.4-41)

```
Отправка формы авторизации
<html>
<head></head>
<body>
  Invalid Token
</body>
</html>
Проверка доступа в интернет
Unexpected character (I) at position 0.
at org.json.simple.parser.Yylex.yylex(Yylex.java:610)
at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)
at org.json.simple.parser.JSONParser.parse(JSONParser.java:118)
at org.json.simple.parser.JSONParser.parse(JSONParser.java:81)
at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
at pw.thedrhax.mosmetro.authenticator.networks.MosMetro.connect(MosMetro.java:138)
at pw.thedrhax.mosmetro.authenticator.Authenticator.start(Authenticator.java:62)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:137)
at pw.thedrhax.mosmetro.activities.DebugActivity$AuthTask.doInBackground(DebugActivity.java:114)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by TheDrHax** [comment]
Похоже на ошибку в обработке Cookies. Если это действительно так, то непонятно, как оно раньше работало.

![screenshot_20161119-164236 01](https://cloud.githubusercontent.com/assets/6968908/20455875/6d790a38-ae77-11e6-9298-94e4b26ace92.png)

**Comment by TheDrHax** [comment]
Последний патч был полезен для общего развития, но он не исправил конкретно эту проблему.

Предположительно, сервер требует CSRF токен, который раньше передавался в качестве скрытого поля формы, а после обновления алгоритма до второй версии пропал из запросов и стал не нужен. Похоже, на сервере авторизации снова включили требование этого токена, но уже в виде заголовка X-CSRF-Token.
